# Generated by Django 5.0.6 on 2024-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_dob',
            field=models.DateField(),
        ),
    ]
