# Generated by Django 5.0.6 on 2024-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0002_alter_userregister_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Quotefortask', models.TextField(max_length=100)),
                ('imagefortask', models.ImageField(upload_to='imagefortask/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
