# Generated by Django 5.0.6 on 2024-07-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0004_daytasks_completed_usertaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfluentflare.userregister'),
        ),
    ]
