# Generated by Django 5.0.6 on 2024-07-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0005_alter_usertaskstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
