# Generated by Django 5.0.6 on 2024-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0007_daytasks_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
