# Generated by Django 5.0.6 on 2024-08-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0009_progressbar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseredirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfluentflare.userregister')),
            ],
        ),
    ]
