# Generated by Django 5.0.6 on 2024-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0011_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
    ]
