# Generated by Django 5.0.6 on 2024-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0013_daytasks_exercise1_daytasks_exercise2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytasks',
            name='headingforexercise',
            field=models.TextField(null=True),
        ),
    ]
