# Generated by Django 5.0.6 on 2024-08-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0014_daytasks_headingforexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytasks',
            name='exercise1ans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daytasks',
            name='exercise2ans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daytasks',
            name='exercise3ans',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
