# Generated by Django 5.0.6 on 2024-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0016_daytasks_timeduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
