# Generated by Django 5.0.6 on 2024-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0017_userregister_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
            ],
        ),
    ]
