# Generated by Django 5.0.6 on 2024-08-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0018_grouplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
