# Generated by Django 5.0.6 on 2024-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
