# Generated by Django 5.0.6 on 2024-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0022_usermessage_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
