# Generated by Django 5.0.6 on 2024-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0023_paymentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/user.png', null=True, upload_to='profile_pics/'),
        ),
    ]
