# Generated by Django 5.0.6 on 2024-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='user_language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
