# Generated by Django 5.0.6 on 2024-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0028_userregister_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_language',
            field=models.CharField(choices=[('Malayalam', 'Malayalam'), ('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil')], default='English', max_length=50),
        ),
    ]
