# Generated by Django 5.0.6 on 2024-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0029_alter_userregister_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentprice',
            name='payment_QRCODE',
            field=models.ImageField(blank=True, null=True, upload_to='payment_QRCODE/'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
