# Generated by Django 5.0.6 on 2024-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0033_userregister_amountpaid_userregister_howmuchperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='howmuchperuser',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
