# Generated by Django 5.0.6 on 2024-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0035_promoterpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterpayment',
            name='amount',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='promoterpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
