# Generated by Django 5.0.6 on 2024-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0036_promoterpayment_amount_promoterpayment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
