# Generated by Django 5.0.6 on 2024-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfluentflare', '0037_alter_promoterpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprice',
            name='offer_payment_QRCODE',
            field=models.ImageField(blank=True, null=True, upload_to='offer_payment_QRCODE/'),
        ),
    ]
